config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'

  get 'static_pages/about'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  resources :statuses
  resources :user_comments
  resources :users, only: [:index, :show]
  resources :tags
  resources :taggings
  resources :facilities, only: [:index, :show]

  root to: 'static_pages#home'

  get 'tagged', :to => 'statuses#tagged', :as => :tagged
  get 'statuses/:id/liked', :to => 'statuses#add_to_favourities', :as => :add_to_favourities
  get 'statuses/:id/unliked', :to => 'statuses#remove_from_favourities', :as => :remove_from_favourities
  get 'statuses/:id/report', :to => 'statuses#report', :as => :report

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      redirect_to statuses_path
    end
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div id="about" class="row">
  <div class="col-md-5">
    <div class="box-effect padding-text" style="margin:10px 10px 0px 0px;">
      <h3>About NUSGhoss</h3>
      <p>
        Having lecture theatres and seminar rooms which can allocate more than 100 students, it is not possible to recognize all students,
        taking the same module or listening to the same set of lecture. There is almost no communication among them, and where there is,
        it is with people whom are already known of or become buddies. Students tend to move around in their own groups in the campus.
      </p><p>
        Besides, due to random allocation from tutorial balloting or short duration of tutorial lessons, sometimes,
        despite attending the same tutorial class over the whole semester, not all classmates become acquaintances to students.
        Within the school, within the course, or even among the students taking the same module,
        the social circle of students remains very limited.
      </p><p>
        In order to overcome this issue, NUS Ghoss (NUS Ghost Gossip) would provide a platform to share fun and interesting stories about school mates,
        lecturers, tutors, or school related topics on modules and facilities. Users can develop familiarity with other users by going
        through the posts about them, and even can discover new friends. With anonymity, users can speak up their thoughts, views,
        opinions without a burden. Ultimately, the app aims to bring togetherness for NUS students and staffs.
      </p>
    </div>
  </div>
  <div class="col-md-7">
    <div class="box-effect padding-text" style="margin-top:10px">
      <h3>User Guide</h3>
      <table>
        <tr>
          <td>
            <p>Sharing stories</p>
          </td>
          <td>
            <p>
              User can post statuses with “+” button at the bottom of the app page.
              To do this, user must be a registered user of the app.
              In the status, user MUST mention other users or facilities, of which the status is about, through tags.
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <p>Searching posts (by User/Facility)</p>
          </td>
          <td>
            <p>
              A search bar is available on the top right corner of the app page.
              User can type in part of user name or facility name or status content in the search bar.
              Alternative ways are through navigation links, Users and Facilities. &amp by tags.
            </p>
          </td>
        </tr>
      </table>
    </div>

  </div>
</div>

app/views/static_pages/home.html.erb
<style media="screen">
  .round-button{
    display: none;
  }

  div#alert-message, div#notice-message{
  	position: absolute;
  	z-index: 1000;
  	width:80%;
  	right:10%;
  	left:10%;
  }
</style>
<div class="wrapper">
  <%= image_tag "homepage.jpg", :class=>"full-banner-image" %>
  <div id="home-intro">
    <h3>NUSGhoss</h3>
    <p>Interact with other fellows</p>
    <%= link_to "Learn more..", static_pages_about_path %>
  </div>
</div>