config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'

  get 'static_pages/about'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  resources :statuses
  resources :user_comments
  resources :users, only: [:index, :show]
  resources :tags
  resources :taggings
  resources :facilities, only: [:index, :show]

  root to: 'static_pages#home'

  get 'tagged', :to => 'statuses#tagged', :as => :tagged
  get 'statuses/:id/liked', :to => 'statuses#add_to_favourities', :as => :add_to_favourities
  get 'statuses/:id/unliked', :to => 'statuses#remove_from_favourities', :as => :remove_from_favourities
  get 'statuses/:id/report', :to => 'statuses#report', :as => :report

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy, :add_to_favourities, :remove_from_favourities, :report]
  before_action :authenticate_user!, except: [:index, :show, :tagged]
  before_action :find_tagged_statuses, only: [:tagged]
  # GET /statuses
  # GET /statuses.json
  def index
    @q = Status.ransack(params[:q])
    @statuses = @q.result(distinct:true).includes(:tags).order("created_at DESC").paginate(:page => params[:page], :per_page => 10);
    @popular_statuses = Status.joins("LEFT OUTER JOIN Votes ON votes.votable_id = statuses.id").group("statuses.id").order("COUNT(votes.id) DESC").having("COUNT(votes.id) != 0").limit(10)
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @user_comment = UserComment.new(:status_id => @status.id)
    if user_signed_in?
      if @status.tags.any?
        @status.tags.each do |tag|
          if current_user.ivle_name == tag.name || current_user.profile_name == tag.name
            @tagged_statuses = true
          end
        end
      end
    end
  end

  # GET /statuses/new
  def new
    @status = current_user.statuses.build
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.build(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to statuses_url, notice: 'Status was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def tagged
      @tag = ActsAsTaggableOn::Tag.find_by_name(params[:tag])
      unless @user
        @statuses = Status.tagged_with(params[:tag]).order("created_at DESC")
      end
  end

  def add_to_favourities
    @status.liked_by current_user
    redirect_to @status
  end

  def remove_from_favourities
    @status.unliked_by current_user
    redirect_to @status
  end

  def report
    @status.update_attributes :reported => !@status.reported
    redirect_to @status, notice: 'You have reported this status of having abusive content.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    def find_tagged_statuses
      @user = User.search(params[:tag])
      if @user
        @statuses = Status.tagged_with(@user.ivle_name).order("created_at DESC")
        unless @user.ivle_name == @user.profile_name
          @statuses += Status.tagged_with(@user.profile_name).order("created_at DESC")
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:user_id, :content, :reported, :tag_list)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
	include ActsAsTaggableOn::TagsHelper
end

app/views/statuses/_comment.html.erb
<div class="comment">
	<i><%= comment.content %></i>
	<div class="meta">
		<%= time_ago_in_words(comment.created_at) + " ago " %> 
		<% if comment.user == current_user %>
			| <%= link_to "Edit", edit_user_comment_path(comment) %>
			| <%= link_to "Delete", comment,  method: :delete, data: { confirm: "Are you sure you want to delete this?"} %>
		<% end %>
	</div>
</div>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p><%= f.label :tags, "* Tags (separated by commas)", :class => "small-text gray", :id=>"edit_tag_list"  %></p>
  <p><%= f.text_area :tag_list, :class => "text required form-control" %></p>
  <div class="field edit-status-content"><%= f.input :content %><br></div>
  <div class="form-actions">
    <%= f.button :submit, :class=> "status-submit-button center" %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<div class="status-show-wrapper">
  <div id="edit-status-container" class="show-status-container">
    <h1>Editing Status</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @status %> |
    <%= link_to 'Back', statuses_path %>

  </div>
</div>

app/views/statuses/index.html.erb
<div id="news-feed" class="col-md-8">
  <div class="box-effect">
    <div class="page-header">
      <h1>News Feed</h1>
    </div>
    <div id="all-posts">
      <% if @statuses.each do |status| %>
        <div class="status">
          <p><%= link_to status.content, status %></p>
          <div class = "tag">
            <% if status.tags.any? %>
              <p>Tags:
              <% status.tags.each do |tag| %>
                <% if User.search(tag.name) %>
                  <%= link_to "@"+tag.name, tagged_url(:tag => tag.name) %>
                <% end %>
                <% if Facility.find_by_name(tag.name) %>
                  <%= link_to "#"+tag.name, tagged_url(:tag => tag.name) %>
                <% end %>
              <% end %>
              </p>
            <% end %>
          </div>
          <div class="meta">
            <%= time_ago_in_words(status.created_at) + " ago " %>
            | <%= status.user_comments.count %> comment(s)
            | <%= status.get_likes.size %> pick(s)
          </div>
        </div>
      <% end.empty? %>
        <p>There are no statuses yet.</p>
      <% end %>
      <% if @statuses.length > 0 %>
        <%= will_paginate @statuses %>
      <% end %>
    </div>
  </div>
</div>

<div id="index-side-bar" class="col-md-4">
  <div id="popular-tag-box" class="box-effect">
    <% if popular_tags.any? %>
      <div id="popular-header">
          <h3>Most Popular Tag(s)</h3>
      </div>
      <div id="popular-tags">
        <% popular_tags.each do |tag| %>
          <% if User.search(tag.name) %>
            <%= link_to "@"+tag.name, tagged_url(:tag => tag.name) %>
          <% end %>
          <% if Facility.find_by_name(tag.name) %>
            <%= link_to "#"+tag.name, tagged_url(:tag => tag.name) %>
          <% end %>
        <% end %>
      <% end %>
      </div>
  </div>
  <% if @popular_statuses.any? %>
    <div id="popular-status-container" class="col-lg-12 col-md-4">
      <div id="popular-status-box" class="box-effect">
        <div id="popular-header">
          <h3>Most Popular Status(es)</h3>
        </div>
        <div id="all-posts" style="border: 1px solid #6ADA4A;">
          <% @popular_statuses.each do |status| %>
            <div class="status" style="margin-bottom:20px;" >
              <p>"<i><%= link_to status.content, status %></i>"</p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/statuses/new.html.erb
<div id="status-form" class="show-status-container">
  <div class="status-form-header">
      <h1>New Status</h1>
  </div>
  <div class="status-form-body">
      <%= render 'form' %>
      <%= link_to 'Back', statuses_path, class: "btn btn-default back-button" %>
  </div>
  <div class="status-form-footer">

  </div>
</div>

app/views/statuses/show.html.erb
<div class="status-show-wrapper">
  <div class="show-status-container">
    <div id="status-header" class="row">
      <div class="col-md-8">
        <div id="status-link">
          <%= link_to 'Back', statuses_path %>
          <% if user_signed_in? %>
            <% if @status.user == current_user %>
              | <%= link_to 'Edit', edit_status_path(@status) %>
            <% end %>
            <% if @status.user == current_user || @tagged_statuses %>
               | <%= link_to "Delete", @status, method: :delete, data: { confirm: "Are you sure you want to delete this?"} %>
            <% else %>
              <% if current_user.liked? @status %>
                | <%= link_to "Remove from Favourities", remove_from_favourities_url(@status) %>
              <% else %>
                | <%= link_to "Add to Favourities", add_to_favourities_url(@status) %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-md-4">
        <div id="status-report">
          <p class="report">
            <% unless @status.reported? %>
              <strong><small><%= link_to 'Report!', report_url(@status), data: { confirm: "Are you sure you want to report this?"}  %></small></strong>
            <% else %>
              <small>This status is reported of having abusive content.</small>
            <% end %>
          </p>
        </div>
      </div>
    </div> <!-- row end -->

    <div id="status-content">
      <p>
        <%= @status.content %>
      </p>
    </div>

    <div class="row">
        <div class="col-md-6">
          <div id="status-tag" class = "tag">
            <% if @status.tags.any? %>
            <p class="small-text gray">
              <strong>Tags:</strong>
              <% @status.tags.each do |tag| %>
                <% if User.search(tag.name) %>
                  <%= link_to "@"+tag.name, tagged_url(:tag => tag.name) %>
                <% end %>
                <% if Facility.find_by_name(tag.name) %>
                  <%= link_to "#"+tag.name, tagged_url(:tag => tag.name) %>
                <% end %>
              <% end %>
            </p>
            <% end %>
          </div>
          <div class="status-comment-info">
            <p class="small-text gray"><strong><%= @status.user_comments.count %> comment(s)</strong> | <strong><%= @status.get_likes.size %> pick(s) </strong></p>

          </div>

        </div>
        <div class="col-md-6">
          <div id="status-info" class="small-text gray">
            <p>
              <strong>Created at:</strong>
              <%= @status.created_at.strftime("%b %d %Y %r") %>
            </p>
            <p>
              <strong>Updated at:</strong>
              <%= @status.updated_at.strftime("%b %d %Y %r") %>
            </p>
          </div>
        </div>
    </div>  <!-- row end -->



    <div id="status-comment" class="comment">
      <%= render :partial => 'comment', :collection => @status.user_comments.order("created_at DESC") %>
    	<% if user_signed_in? %>
    	  <h3>Add a Comment</h3>
    	  <%= render :partial =>'user_comments/form' %>
      <% end %>
    </div>

  </div>
</div>

app/views/statuses/tagged.html.erb
<div class="page-header">
  <h1>
    <% if User.search(@tag.name) %>
      <%= "@"+@tag.name %>
    <% end %>
    <% if Facility.find_by_name(@tag.name) %>
      <%= "#"+@tag.name %>
    <% end %>
  </h1>  
</div>
<% @statuses.each do |status| %>
  <div class="status">
    <p><%= link_to status.content, status %></p>
    <div class = "tag">
      <% status.tags.each do |tag| %>
        <% if User.search(tag.name) %>
          <%= link_to "@"+tag.name, tagged_url(:tag => tag.name) %>
        <% end %>
        <% if Facility.find_by_name(tag.name) %>
          <%= link_to "#"+tag.name, tagged_url(:tag => tag.name) %>
        <% end %>
      <% end %>
    </div>
    <div class="meta">
      <%= time_ago_in_words(status.created_at) + " ago " %> 
      | <%= status.user_comments.count %> comment(s)
      | <%= status.get_likes.size %> pick(s) 
    </div>
  </div>
<% end %> 
<%= link_to 'Back', statuses_path %>
| <%= link_to 'Home', root_path %>