config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'

  get 'static_pages/about'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  resources :statuses
  resources :user_comments
  resources :users, only: [:index, :show]
  resources :tags
  resources :taggings
  resources :facilities, only: [:index, :show]

  root to: 'static_pages#home'

  get 'tagged', :to => 'statuses#tagged', :as => :tagged
  get 'statuses/:id/liked', :to => 'statuses#add_to_favourities', :as => :add_to_favourities
  get 'statuses/:id/unliked', :to => 'statuses#remove_from_favourities', :as => :remove_from_favourities
  get 'statuses/:id/report', :to => 'statuses#report', :as => :report

end

app/views/layouts/application.html.erb
<%= cloudinary_js_config %>
<!DOCTYPE html>
<html>
<head>
  <title>NUSGhoss</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "ivle.js", "sidebar.js", "active_admin.js", "bootstrap.js" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
	  	<div class="container-fluid">
	    	<div class="navbar-header">
              <%= link_to "NUSGhoss", root_path, {:class=>"navbar-brand"} %>
            	<div class="search">
                <%= search_form_for @q, :html => { :class => "form-wrapper cf" } do |f| %>
            	  <%= f.text_field :tags_name_or_content_cont, :id => "search-textfield" %>
            	    <%= f.submit "Search", :id => 'search-button'  %>
                  <% end %>
              </div>
              <button type="button" class="navbar-toggle hidden-md hidden-lg" data-toggle="sidebar" data-target=".sidebar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
        </div>

        <!-- Main Navbar -->
        <ul class="nav navbar-nav pull-right" id="menu-navbar">
            <li><%= link_to "Feed", statuses_path, {:class => "navbar-brand"} %></li>
            <li><%= link_to "Users", users_path, {:class => "navbar-brand"} %></li>
            <li><%= link_to "Facilities", facilities_path, {:class => "navbar-brand"} %></li>
            <% if user_signed_in? %>
            <li><%= link_to current_user.profile_name, "/users/" + current_user.id.to_s %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %><li>
            <% else %>
            <li><a href="#" onclick="ivleValidation(this.id);return false;" id='register-nav-button'>Register</a></li>
            <li><%= link_to "Log in", new_user_session_path %></li>
            <% end %>
        </ul>

        <!-- Mobile Sliding Menu -->
        <div class="navbar-collapse col-xs-4 col-sm-3 col-md-2 sidebar sidebar-right sidebar-animate">
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to "Feed", statuses_path %></li>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Facilities", facilities_path %></li>
              <% if user_signed_in? %>
              <li><%= link_to current_user.profile_name, "/users/" + current_user.id.to_s %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %><li>
              <% else %>
              <li><a href="#" onclick="ivleValidation(this.id);return false;" id='register-side-button'>Register</a></li>
              <li><%= link_to "Log in", new_user_session_path %></li>
              <% end %>
            </ul>
        </div>
	  	</div>
	</nav>
  <div class="page-wrapper">
    <div class="container">
      <div id="alert-message" class="">
        <p class="notice message"><%= notice %></p>
        <p class="alert message"><%= alert %></p>
      </div>
      <%= yield %>
    </div>
  </div>

  <% unless current_page?(new_status_path) %>
    <div class="round-button">
      <div class="round-button-circle">
          <%= link_to "+", new_status_path, class:"roundbutton create", id:"create-button" %>
      </div>
    </div>
  <% end %>
	<script type="text/javascript">
    $('.message').each(function() {
      var $this = $(this);
      if($this.html().replace(/\s|&nbsp;/g, '').length == 0)
          $this.remove();
    });
	</script>
</body>
</html>